# =========================
# constants.py
# Constantes globales del bot
# =========================


# =========================
# ESTADOS GENERALES
# =========================
ESTADO_CORRECTA = "CORRECTA"
ESTADO_OBSERVADA = "OBSERVADA"


# =========================
# ESTADOS DE SESIÓN
# =========================
STATE_IDLE = "IDLE"
STATE_START = "START"

STATE_SELECT_EMPRESA = "SELECT_EMPRESA"
STATE_SELECT_SUPERVISOR = "SELECT_SUPERVISOR"
STATE_SELECT_TECNICO = "SELECT_TECNICO"
STATE_SELECT_CUADRILLA = "SELECT_CUADRILLA"
STATE_SELECT_DISTRITO = "SELECT_DISTRITO"

STATE_MENU_SUPERVISION = "MENU_SUPERVISION"
STATE_MENU_INSTALACION = "MENU_INSTALACION"
STATE_MENU_HERRAMIENTAS = "MENU_HERRAMIENTAS"
STATE_MENU_EPP = "MENU_EPP"
STATE_MENU_EPE = "MENU_EPE"
STATE_MENU_UNIFORMES = "MENU_UNIFORMES"
STATE_MENU_VEHICULO = "MENU_VEHICULO"
STATE_MENU_OPCIONAL = "MENU_OPCIONAL"
STATE_MENU_INFO = "MENU_INFO"

STATE_UPLOAD = "UPLOAD"
STATE_CONFIRMAR = "CONFIRMAR"
STATE_CONFIRM_FINAL = "CONFIRM_FINAL"
STATE_FINALIZADO = "FINALIZADO"

STATE_SEARCH_TECNICO = "SEARCH_TECNICO"
STATE_WAIT_TECNICO_2_DECISION = "WAIT_TECNICO_2_DECISION"
STATE_WAIT_TECNICO_3_DECISION = "WAIT_TECNICO_3_DECISION"
STATE_WAITING_TIPO_SUPERVISION = "WAITING_TIPO_SUPERVISION"
STATE_INPUT_PLACA_UNIDAD = "INPUT_PLACA_UNIDAD"
STATE_INPUT_CODIGO_PEDIDO = "INPUT_CODIGO_PEDIDO"


# =========================
# PASOS DE EVIDENCIA (FLOW PRINCIPAL LEGACY)
# =========================
STEP_FACHADA = "FACHADA"
STEP_CTO = "CTO"
STEP_POTENCIA_CTO = "POTENCIA_CTO"
STEP_CINTILLO = "CINTILLO"
STEP_DROP_DOMICILIO = "DROP_DOMICILIO"
STEP_ANCLAJE = "ANCLAJE"
STEP_ROSETA_POTENCIA = "ROSETA_POTENCIA"
STEP_SPLITTER = "SPLITTER"
STEP_MAC_ONT = "MAC_ONT"
STEP_ONT = "ONT"
STEP_TEST_VELOCIDAD = "TEST_VELOCIDAD"
STEP_ACTA = "ACTA"

# Flujo alterno legacy
STEP_FACHADA_PANORAMICA = "FACHADA_PANORAMICA"
STEP_PLACA_DOMICILIO = "PLACA_DOMICILIO"
STEP_SUMINISTRO = "SUMINISTRO"


# =========================
# PASOS REALES DEL BOT ACTUAL
# =========================
STEP_POSTE = "POSTE"
STEP_RUTA = "RUTA"
STEP_FALSO_TRAMO = "FALSO_TRAMO"
STEP_RESERVA_DOMICILIO = "RESERVA_DOMICILIO"
STEP_ROSETA = "ROSETA"
STEP_EQUIPOS = "EQUIPOS"

STEP_ALICATE_CORTE = "ALICATE_CORTE"
STEP_ALICATE_PINZAS = "ALICATE_PINZAS"
STEP_ALICATE_UNIVERSAL = "ALICATE_UNIVERSAL"
STEP_CRIMPING_TOOL = "CRIMPING_TOOL"
STEP_DESTORNILLADOR_ESTRELLA = "DESTORNILLADOR_ESTRELLA"
STEP_DESTORNILLADOR_PLANO = "DESTORNILLADOR_PLANO"
STEP_MARTILLO = "MARTILLO"
STEP_TESTEADOR_UTP = "TESTEADOR_UTP"
STEP_TALADRO_PERCUSION = "TALADRO_PERCUSION"
STEP_BROCA_CEMENTO_30 = "BROCA_CEMENTO_30"
STEP_BROCA_CEMENTO_15 = "BROCA_CEMENTO_15"
STEP_BROCA_MADERA_15 = "BROCA_MADERA_15"
STEP_WINCHA_PASACABLES = "WINCHA_PASACABLES"
STEP_EXTENSION_AC_20 = "EXTENSION_AC_20"
STEP_ZUNCHADORA = "ZUNCHADORA"
STEP_PORTACARRETE = "PORTACARRETE"

STEP_CASCO_SEGURIDAD = "CASCO_SEGURIDAD"
STEP_BARBIQUEJO = "BARBIQUEJO"
STEP_BOTAS_SEGURIDAD = "BOTAS_SEGURIDAD"
STEP_LENTES_SEGURIDAD = "LENTES_SEGURIDAD"
STEP_GUANTES_BADANA = "GUANTES_BADANA"
STEP_GUANTES_MULTIFLEX = "GUANTES_MULTIFLEX"
STEP_GUANTES_TELA = "GUANTES_TELA"
STEP_GUANTES_DIELECTRICOS = "GUANTES_DIELECTRICOS"
STEP_CINTURON_POSICIONAMIENTO = "CINTURON_POSICIONAMIENTO"

STEP_CONOS = "CONOS"
STEP_BARRAS_RETRACTILES = "BARRAS_RETRACTILES"
STEP_ESCALERA_TIJERA_6 = "ESCALERA_TIJERA_6"
STEP_ESCALERA_TELESCOPICA_28 = "ESCALERA_TELESCOPICA_28"
STEP_REVELADOR_TENSION = "REVELADOR_TENSION"

STEP_POLO = "POLO"
STEP_CHALECO = "CHALECO"
STEP_PANTALON = "PANTALON"
STEP_FOTOCHECK = "FOTOCHECK"

STEP_EXTINTOR = "EXTINTOR"
STEP_BOTIQUIN = "BOTIQUIN"
STEP_LICENCIA_CONDUCIR = "LICENCIA_CONDUCIR"
STEP_SOAT = "SOAT"
STEP_REVISION_TECNICA = "REVISION_TECNICA"
STEP_TARJETA_PROPIEDAD = "TARJETA_PROPIEDAD"
STEP_PARRILLA_PORTAESCALERAS = "PARRILLA_PORTAESCALERAS"
STEP_TACOS_SEGURIDAD = "TACOS_SEGURIDAD"
STEP_LOGOS = "LOGOS"


# =========================
# PASOS OPCIONALES
# =========================
STEP_OPCIONAL_GENERAL = "OPCIONAL_GENERAL"


# =========================
# PASOS DE INFORMACIÓN (NO FOTOS)
# =========================
STEP_INFO_DROP_EXT = "INFO_DROP_EXT"
STEP_INFO_DROP_INT = "INFO_DROP_INT"
STEP_INFO_POSTES = "INFO_POSTES"
STEP_INFO_FALSOS = "INFO_FALSOS"
STEP_INFO_TEMPLADORES = "INFO_TEMPLADORES"
STEP_INFO_RECORRIDO = "INFO_RECORRIDO"
STEP_INFO_VALIDACION_ACTA = "INFO_VALIDACION_ACTA"


# =========================
# LISTAS ORDENADAS
# =========================
FLUJO_PRINCIPAL = [
    STEP_FACHADA,
    STEP_CTO,
    STEP_POTENCIA_CTO,
    STEP_CINTILLO,
    STEP_DROP_DOMICILIO,
    STEP_ANCLAJE,
    STEP_ROSETA_POTENCIA,
    STEP_SPLITTER,
    STEP_MAC_ONT,
    STEP_ONT,
    STEP_TEST_VELOCIDAD,
    STEP_ACTA,
]

FLUJO_INSTALACION_ACTUAL = [
    STEP_CTO,
    STEP_POSTE,
    STEP_RUTA,
    STEP_FALSO_TRAMO,
    STEP_ANCLAJE,
    STEP_RESERVA_DOMICILIO,
    STEP_ROSETA,
    STEP_EQUIPOS,
]


# =========================
# TEXTOS DE AYUDA
# =========================
STEP_HINTS = {
    STEP_FACHADA: "Foto de la fachada del domicilio.",
    STEP_CTO: "Foto clara del CTO.",
    STEP_POTENCIA_CTO: "Captura de medición de potencia en CTO.",
    STEP_CINTILLO: "Cintillo correctamente rotulado.",
    STEP_DROP_DOMICILIO: "Ingreso del drop al domicilio.",
    STEP_ANCLAJE: "Punto de anclaje instalado.",
    STEP_ROSETA_POTENCIA: "Roseta + medición de potencia.",
    STEP_SPLITTER: "Foto panorámica del splitter.",
    STEP_MAC_ONT: "Etiqueta MAC de la ONT.",
    STEP_ONT: "Foto de la ONT instalada.",
    STEP_TEST_VELOCIDAD: "Resultado del test de velocidad.",
    STEP_ACTA: "Acta de instalación firmada.",

    STEP_POSTE: "Foto del poste.",
    STEP_RUTA: "Foto de la ruta del cableado.",
    STEP_FALSO_TRAMO: "Foto del falso tramo.",
    STEP_RESERVA_DOMICILIO: "Foto de la reserva en domicilio.",
    STEP_ROSETA: "Foto de la roseta instalada.",
    STEP_EQUIPOS: "Foto de equipos instalados.",

    STEP_FOTOCHECK: "Foto del fotocheck del personal.",
    STEP_LOGOS: "Foto de los logos visibles en la unidad.",

    STEP_INFO_DROP_EXT: "Indicar ubicación CTO + domicilio + metraje.",
    STEP_INFO_DROP_INT: "Metraje del drop interno.",
    STEP_INFO_POSTES: "Cantidad de postes.",
    STEP_INFO_FALSOS: "Cantidad de falsos tramos.",
    STEP_INFO_TEMPLADORES: "Cantidad de templadores.",
    STEP_INFO_RECORRIDO: "Captura del recorrido.",
    STEP_INFO_VALIDACION_ACTA: "¿Datos del acta son correctos? (SI/NO)",
}


# =========================
# CALLBACK PREFIX
# =========================
CB_START = "START"
CB_CANCEL = "CANCEL"
CB_BACK = "BACK"

CB_EMPRESA = "EMPRESA"
CB_SUPERVISOR = "SUPERVISOR"
CB_TECNICO = "TECNICO"
CB_CUADRILLA = "CUADRILLA"
CB_DISTRITO = "DISTRITO"
CB_TIPO_SUP = "TIPO_SUP"

CB_MENU = "MENU"
CB_STEP = "STEP"
CB_CONFIRM = "CONFIRM"
CB_FINAL = "FINAL"

CB_INFO = "INFO"
CB_OPCIONAL = "OPCIONAL"


# =========================
# MENÚS
# =========================
MENU_SUPERVISION = "MENU_SUPERVISION"
MENU_INSTALACION = "MENU_INSTALACION"
MENU_HERRAMIENTAS = "MENU_HERRAMIENTAS"
MENU_EPP = "MENU_EPP"
MENU_EPE = "MENU_EPE"
MENU_UNIFORMES = "MENU_UNIFORMES"
MENU_VEHICULO = "MENU_VEHICULO"
MENU_OPCIONAL = "MENU_OPCIONAL"
MENU_INFO = "MENU_INFO"
MENU_FINALIZAR = "MENU_FINALIZAR"


# =========================
# EMPRESAS
# =========================
EMPRESA_WIN = "WIN"
EMPRESA_TUFIBRA = "TUFIBRA"


# =========================
# TIPOS DE SUPERVISIÓN
# =========================
TIPO_SUP_CALIENTE = "SUPERVISION EN CALIENTE"
TIPO_SUP_FRIO = "SUPERVISION EN FRIO"


# =========================
# CAMPOS DE SHEETS
# =========================
COL_ID = "ID"
COL_FECHA = "Fecha"
COL_SUPERVISOR = "Supervisor"
COL_TECNICO = "Tecnico"
COL_CUADRILLA = "Cuadrilla"
COL_EMPRESA = "Empresa"
COL_DISTRITO = "Distrito"
COL_ESTADO_FINAL = "Estado_Final"
COL_OBSERVACION = "Observacion"
COL_REGISTRADO_EN = "Registrado_En"
COL_TIPO_SUPERVISION = "Tipo_Supervision"
COL_PLACA_UNIDAD = "Placa_Unidad"


# =========================
# LIMITES
# =========================
MAX_REINTENTOS = 5
MAX_FOTOS_POR_PASO = 8


# =========================
# MENSAJES BASE
# =========================
MSG_BIENVENIDA = "👷‍♂️ Bienvenido al sistema de supervisión."
MSG_SELECCIONA_OPCION = "Selecciona una opción:"
MSG_ERROR = "⚠️ Ocurrió un error. Intenta nuevamente."
MSG_CANCELADO = "❌ Operación cancelada."
MSG_FINALIZADO = "✅ Supervisión finalizada correctamente."


# =========================
# VALIDACIONES
# =========================
RESPUESTA_SI = ["SI", "SÍ", "YES", "OK"]
RESPUESTA_NO = ["NO"]

VALID_TRUE = {"1", "TRUE", "SI", "SÍ", "YES", "Y", "ON", "ACTIVO"}
VALID_FALSE = {"0", "FALSE", "NO", "OFF", "INACTIVO"}


# =========================
# ESTADOS DE ALMUERZO
# =========================
ALM_ESTADO_ACTIVO = "ACTIVO"
ALM_ESTADO_CERRADO = "CERRADO"


# =========================
# DEBUG
# =========================
DEBUG_FLOW = False
DEBUG_SHEETS = False
DEBUG_MEDIA = False